services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    volumes:
      - db_data:/var/www/html/db

volumes:
  db_data:
    driver: local
